#!/bin/bash

echo "Script Name: $0"
echo " User Name: $USER"
echo "User ID: $UID"
echo "Group ID: $GROUPS"
echo "Hostname: $HOSTNAME"
echo "Operating System: $OSTYPE"
echo "Current Shell: $SHELL"
echo " Home Directory: $HOME"
echo " Current Directory: $PWD"
echo "Current Date: $(date)"
echo "Current Time: $(date +%T)"
echo "Current Year: $(date +%Y)"
echo "Current Month: $(date +%m)"
echo "Current Day: $(date +%d)"
echo "Current Date and Time: $(date +%F-%T)"
echo " Number of Arguments: $#"
echo "First Argument: $1"
echo "Second Argument: $2"
echo "Third Argument: $3"
echo " Arguments: $*"   
echo "All variables passed in the script: $@"
echo "All variables passed in the script: $*"
echo "PID of the script: $$"
echo "Exit status of the last command: $?"
echo "Bash version: $BASH_VERSION"
echo "Bash Shell: $BASH"
echo "Bash options: $-"
echo "Bash source file: $BASH_SOURCE"
echo "Bash command: $BASH_COMMAND"  
sleep 20
echo "PID of the last background process: $!"


